language: php
php:
  - "5.5"
  - "5.4"
  - "5.3"
    
services: mysql

env:
  - DB=mysql
  - mysqldatabase=myapp_test
  - mysqlusername=root
  - mysqlpassword=
  - mysqladdress=localhost
  
before_script:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install
  - mysql -e 'create database IF NOT EXISTS myapp_test;' -uroot
  
script: cd phpunit && phpunit --tap -c phpunit.xml --coverage-text

branches:
  only:
    - Just-Framework