language: php
php:
  - "5.5"
  - "5.4"
  - "5.3"
    
services: mysql

env:
  - DB=mysql
  
before_script:
  - mysql -e 'create database IF NOT EXISTS myapp_test;' -uroot
  
script: cd phpunit && phpunit --tap -c phpunit.xml --coverage-text

branches:
  only:
    - Just-Framework