language: php
php:
  - "5.5"
  - "5.4"
  - "5.3"
    
services: mysql

env:
  - DB=mysql
  
before_script:
  - mysql -e 'create database IF NOT EXISTS myapp_test;' -uroot
  - pear channel-discover pear.phpunit.de
  - pear install phpunit/PHP_Invoker
  - pear install phpunit/DbUnit
  - pear install phpunit/PHPUnit_Selenium
  - pear install phpunit/PHPUnit_Story
  
script: cd phpunit && phpunit --tap -c phpunit.xml --coverage-text

branches:
  only:
    - Just-Framework