language: php
php:
  - "5.5"
  - "5.4"
  - "5.3"
    
services: mysql
  
before_script:
  - mysql -e 'create database myapp_test;'
script: cd phpunit && phpunit --tap -c phpunit.xml

branches:
  only:
    - Just-Framework